import React from "react"
import Header from "../components/Header"
import AdminCss from "../styles/adminCss.css"
import {useState, useEffect} from "react"


function Admin(){
    
    const [email11, setEmail11] = useState([])

    const [back1, setBack1] = useState("");
    const [back2, setBack2] = useState("");
    const [back3, setBack3] = useState("");
    const [back4, setBack4] = useState("");
    const [back5, setBack5] = useState("");
    const [back6, setBack6] = useState("");
    const [back7, setBack7] = useState("");
    const [back8, setBack8] = useState("");
    const [back9, setBack9] = useState("");
    const [back10, setBack10] = useState("");
    const [back11, setBack11] = useState("");
    const [back12, setBack12] = useState("");
    const [back13, setBack13] = useState("");
    const [back14, setBack14] = useState("");
    const [back15, setBack15] = useState("");
    const [back16, setBack16] = useState("");
    const [back17, setBack17] = useState("");
    const [back18, setBack18] = useState("");
    const [back19, setBack19] = useState("");
    const [back20, setBack20] = useState("");
    const [back21, setBack21] = useState("");
    const [back22, setBack22] = useState("");
    const [back23, setBack23] = useState("");
    const [back24, setBack24] = useState("");
    const [back25, setBack25] = useState("");
    const [back26, setBack26] = useState("");
    const [back27, setBack27] = useState("");
    const [back28, setBack28] = useState("");
    const [back29, setBack29] = useState("");
    const [back30, setBack30] = useState("");


    function setback1(){
        setBack1("orange")
        setBack2("")
        setBack3("")
        setBack4("")
        setBack5("")
        setBack6("")
        setBack7("")
        setBack8("")
        setBack9("")
        setBack10("")
        setBack11("")
        setBack12("")
        setBack13("")
        setBack14("")
        setBack15("")
        setBack16("")
        setBack17("")
        setBack18("")
        setBack19("")
        setBack20("")
        setBack21("")
        setBack22("")
        setBack23("")
        setBack24("")
        setBack25("")
        setBack26("")
        setBack27("")
        setBack28("")
        setBack29("")
        setBack30("")
    }
    function setback2(){
        setBack1("")
        setBack2("orange")
        setBack3("")
        setBack4("")
        setBack5("")
        setBack6("")
        setBack7("")
        setBack8("")
        setBack9("")
        setBack10("")
        setBack11("")
        setBack12("")
        setBack13("")
        setBack14("")
        setBack15("")
        setBack16("")
        setBack17("")
        setBack18("")
        setBack19("")
        setBack20("")
        setBack21("")
        setBack22("")
        setBack23("")
        setBack24("")
        setBack25("")
        setBack26("")
        setBack27("")
        setBack28("")
        setBack29("")
        setBack30("")
    }
    function setback3(){
        setBack1("")
        setBack2("")
        setBack3("orange")
        setBack4("")
        setBack5("")
        setBack6("")
        setBack7("")
        setBack8("")
        setBack9("")
        setBack10("")
        setBack11("")
        setBack12("")
        setBack13("")
        setBack14("")
        setBack15("")
        setBack16("")
        setBack17("")
        setBack18("")
        setBack19("")
        setBack20("")
        setBack21("")
        setBack22("")
        setBack23("")
        setBack24("")
        setBack25("")
        setBack26("")
        setBack27("")
        setBack28("")
        setBack29("")
        setBack30("")
    }
    function setback4(){
        setBack1("")
        setBack2("")
        setBack3("")
        setBack4("orange")
        setBack5("")
        setBack6("")
        setBack7("")
        setBack8("")
        setBack9("")
        setBack10("")
        setBack11("")
        setBack12("")
        setBack13("")
        setBack14("")
        setBack15("")
        setBack16("")
        setBack17("")
        setBack18("")
        setBack19("")
        setBack20("")
        setBack21("")
        setBack22("")
        setBack23("")
        setBack24("")
        setBack25("")
        setBack26("")
        setBack27("")
        setBack28("")
        setBack29("")
        setBack30("")
    }
    function setback5(){
        setBack1("")
        setBack2("")
        setBack3("")
        setBack4("")
        setBack5("orange")
        setBack6("")
        setBack7("")
        setBack8("")
        setBack9("")
        setBack10("")
        setBack11("")
        setBack12("")
        setBack13("")
        setBack14("")
        setBack15("")
        setBack16("")
        setBack17("")
        setBack18("")
        setBack19("")
        setBack20("")
        setBack21("")
        setBack22("")
        setBack23("")
        setBack24("")
        setBack25("")
        setBack26("")
        setBack27("")
        setBack28("")
        setBack29("")
        setBack30("")
    }
    function setback6(){
        setBack1("")
        setBack2("")
        setBack3("")
        setBack4("")
        setBack5("")
        setBack6("orange")
        setBack7("")
        setBack8("")
        setBack9("")
        setBack10("")
        setBack11("")
        setBack12("")
        setBack13("")
        setBack14("")
        setBack15("")
        setBack16("")
        setBack17("")
        setBack18("")
        setBack19("")
        setBack20("")
        setBack21("")
        setBack22("")
        setBack23("")
        setBack24("")
        setBack25("")
        setBack26("")
        setBack27("")
        setBack28("")
        setBack29("")
        setBack30("")
    }
    function setback7(){
        setBack1("")
        setBack2("")
        setBack3("")
        setBack4("")
        setBack5("")
        setBack6("")
        setBack7("orange")
        setBack8("")
        setBack9("")
        setBack10("")
        setBack11("")
        setBack12("")
        setBack13("")
        setBack14("")
        setBack15("")
        setBack16("")
        setBack17("")
        setBack18("")
        setBack19("")
        setBack20("")
        setBack21("")
        setBack22("")
        setBack23("")
        setBack24("")
        setBack25("")
        setBack26("")
        setBack27("")
        setBack28("")
        setBack29("")
        setBack30("")
    }
    function setback8(){
        setBack1("")
        setBack2("")
        setBack3("")
        setBack4("")
        setBack5("")
        setBack6("")
        setBack7("")
        setBack8("orange")
        setBack9("")
        setBack10("")
        setBack11("")
        setBack12("")
        setBack13("")
        setBack14("")
        setBack15("")
        setBack16("")
        setBack17("")
        setBack18("")
        setBack19("")
        setBack20("")
        setBack21("")
        setBack22("")
        setBack23("")
        setBack24("")
        setBack25("")
        setBack26("")
        setBack27("")
        setBack28("")
        setBack29("")
        setBack30("")
    }
    function setback9(){
        setBack1("")
        setBack2("")
        setBack3("")
        setBack4("")
        setBack5("")
        setBack6("")
        setBack7("")
        setBack8("")
        setBack9("orange")
        setBack10("")
        setBack11("")
        setBack12("")
        setBack13("")
        setBack14("")
        setBack15("")
        setBack16("")
        setBack17("")
        setBack18("")
        setBack19("")
        setBack20("")
        setBack21("")
        setBack22("")
        setBack23("")
        setBack24("")
        setBack25("")
        setBack26("")
        setBack27("")
        setBack28("")
        setBack29("")
        setBack30("")
    }
    function setback10(){
        setBack1("")
        setBack2("")
        setBack3("")
        setBack4("")
        setBack5("")
        setBack6("")
        setBack7("")
        setBack8("")
        setBack9("")
        setBack10("orange")
        setBack11("")
        setBack12("")
        setBack13("")
        setBack14("")
        setBack15("")
        setBack16("")
        setBack17("")
        setBack18("")
        setBack19("")
        setBack20("")
        setBack21("")
        setBack22("")
        setBack23("")
        setBack24("")
        setBack25("")
        setBack26("")
        setBack27("")
        setBack28("")
        setBack29("")
        setBack30("")
    }
    function setback11(){
        setBack1("")
        setBack2("")
        setBack3("")
        setBack4("")
        setBack5("")
        setBack6("")
        setBack7("")
        setBack8("")
        setBack9("")
        setBack10("")
        setBack11("orange")
        setBack12("")
        setBack13("")
        setBack14("")
        setBack15("")
        setBack16("")
        setBack17("")
        setBack18("")
        setBack19("")
        setBack20("")
        setBack21("")
        setBack22("")
        setBack23("")
        setBack24("")
        setBack25("")
        setBack26("")
        setBack27("")
        setBack28("")
        setBack29("")
        setBack30("")
    }
    function setback12(){
        setBack1("")
        setBack2("")
        setBack3("")
        setBack4("")
        setBack5("")
        setBack6("")
        setBack7("")
        setBack8("")
        setBack9("")
        setBack10("")
        setBack11("")
        setBack12("orange")
        setBack13("")
        setBack14("")
        setBack15("")
        setBack16("")
        setBack17("")
        setBack18("")
        setBack19("")
        setBack20("")
        setBack21("")
        setBack22("")
        setBack23("")
        setBack24("")
        setBack25("")
        setBack26("")
        setBack27("")
        setBack28("")
        setBack29("")
        setBack30("")
    }
    function setback13(){
        setBack1("")
        setBack2("")
        setBack3("")
        setBack4("")
        setBack5("")
        setBack6("")
        setBack7("")
        setBack8("")
        setBack9("")
        setBack10("")
        setBack11("")
        setBack12("")
        setBack13("orange")
        setBack14("")
        setBack15("")
        setBack16("")
        setBack17("")
        setBack18("")
        setBack19("")
        setBack20("")
        setBack21("")
        setBack22("")
        setBack23("")
        setBack24("")
        setBack25("")
        setBack26("")
        setBack27("")
        setBack28("")
        setBack29("")
        setBack30("")
    }
    function setback14(){
        setBack1("")
        setBack2("")
        setBack3("")
        setBack4("")
        setBack5("")
        setBack6("")
        setBack7("")
        setBack8("")
        setBack9("")
        setBack10("")
        setBack11("")
        setBack12("")
        setBack13("")
        setBack14("orange")
        setBack15("")
        setBack16("")
        setBack17("")
        setBack18("")
        setBack19("")
        setBack20("")
        setBack21("")
        setBack22("")
        setBack23("")
        setBack24("")
        setBack25("")
        setBack26("")
        setBack27("")
        setBack28("")
        setBack29("")
        setBack30("")
    }
    function setback15(){
        setBack1("")
        setBack2("")
        setBack3("")
        setBack4("")
        setBack5("")
        setBack6("")
        setBack7("")
        setBack8("")
        setBack9("")
        setBack10("")
        setBack11("")
        setBack12("")
        setBack13("")
        setBack14("")
        setBack15("orange")
        setBack16("")
        setBack17("")
        setBack18("")
        setBack19("")
        setBack20("")
        setBack21("")
        setBack22("")
        setBack23("")
        setBack24("")
        setBack25("")
        setBack26("")
        setBack27("")
        setBack28("")
        setBack29("")
        setBack30("")
    }
    function setback16(){
        setBack1("")
        setBack2("")
        setBack3("")
        setBack4("")
        setBack5("")
        setBack6("")
        setBack7("")
        setBack8("")
        setBack9("")
        setBack10("")
        setBack11("")
        setBack12("")
        setBack13("")
        setBack14("")
        setBack15("")
        setBack16("orange")
        setBack17("")
        setBack18("")
        setBack19("")
        setBack20("")
        setBack21("")
        setBack22("")
        setBack23("")
        setBack24("")
        setBack25("")
        setBack26("")
        setBack27("")
        setBack28("")
        setBack29("")
        setBack30("")
    }
    function setback17(){
        setBack1("")
        setBack2("")
        setBack3("")
        setBack4("")
        setBack5("")
        setBack6("")
        setBack7("")
        setBack8("")
        setBack9("")
        setBack10("")
        setBack11("")
        setBack12("")
        setBack13("")
        setBack14("")
        setBack15("")
        setBack16("")
        setBack17("orange")
        setBack18("")
        setBack19("")
        setBack20("")
        setBack21("")
        setBack22("")
        setBack23("")
        setBack24("")
        setBack25("")
        setBack26("")
        setBack27("")
        setBack28("")
        setBack29("")
        setBack30("")
    }
    function setback18(){
        setBack1("")
        setBack2("")
        setBack3("")
        setBack4("")
        setBack5("")
        setBack6("")
        setBack7("")
        setBack8("")
        setBack9("")
        setBack10("")
        setBack11("")
        setBack12("")
        setBack13("")
        setBack14("")
        setBack15("")
        setBack16("")
        setBack17("")
        setBack18("orange")
        setBack19("")
        setBack20("")
        setBack21("")
        setBack22("")
        setBack23("")
        setBack24("")
        setBack25("")
        setBack26("")
        setBack27("")
        setBack28("")
        setBack29("")
        setBack30("")
    }
    function setback19(){
        setBack1("")
        setBack2("")
        setBack3("")
        setBack4("")
        setBack5("")
        setBack6("")
        setBack7("")
        setBack8("")
        setBack9("")
        setBack10("")
        setBack11("")
        setBack12("")
        setBack13("")
        setBack14("")
        setBack15("")
        setBack16("")
        setBack17("")
        setBack18("")
        setBack19("orange")
        setBack20("")
        setBack21("")
        setBack22("")
        setBack23("")
        setBack24("")
        setBack25("")
        setBack26("")
        setBack27("")
        setBack28("")
        setBack29("")
        setBack30("")
    }
    function setback20(){
        setBack1("")
        setBack2("")
        setBack3("")
        setBack4("")
        setBack5("")
        setBack6("")
        setBack7("")
        setBack8("")
        setBack9("")
        setBack10("")
        setBack11("")
        setBack12("")
        setBack13("")
        setBack14("")
        setBack15("")
        setBack16("")
        setBack17("")
        setBack18("")
        setBack19("")
        setBack20("orange")
        setBack21("")
        setBack22("")
        setBack23("")
        setBack24("")
        setBack25("")
        setBack26("")
        setBack27("")
        setBack28("")
        setBack29("")
        setBack30("")
    }
    function setback21(){
        setBack1("")
        setBack2("")
        setBack3("")
        setBack4("")
        setBack5("")
        setBack6("")
        setBack7("")
        setBack8("")
        setBack9("")
        setBack10("")
        setBack11("")
        setBack12("")
        setBack13("")
        setBack14("")
        setBack15("")
        setBack16("")
        setBack17("")
        setBack18("")
        setBack19("")
        setBack20("")
        setBack21("orange")
        setBack22("")
        setBack23("")
        setBack24("")
        setBack25("")
        setBack26("")
        setBack27("")
        setBack28("")
        setBack29("")
        setBack30("")
    }
    function setback22(){
        setBack1("")
        setBack2("")
        setBack3("")
        setBack4("")
        setBack5("")
        setBack6("")
        setBack7("")
        setBack8("")
        setBack9("")
        setBack10("")
        setBack11("")
        setBack12("")
        setBack13("")
        setBack14("")
        setBack15("")
        setBack16("")
        setBack17("")
        setBack18("")
        setBack19("")
        setBack20("")
        setBack21("")
        setBack22("orange")
        setBack23("")
        setBack24("")
        setBack25("")
        setBack26("")
        setBack27("")
        setBack28("")
        setBack29("")
        setBack30("")
    }
    function setback23(){
        setBack1("")
        setBack2("")
        setBack3("")
        setBack4("")
        setBack5("")
        setBack6("")
        setBack7("")
        setBack8("")
        setBack9("")
        setBack10("")
        setBack11("")
        setBack12("")
        setBack13("")
        setBack14("")
        setBack15("")
        setBack16("")
        setBack17("")
        setBack18("")
        setBack19("")
        setBack20("")
        setBack21("")
        setBack22("")
        setBack23("orange")
        setBack24("")
        setBack25("")
        setBack26("")
        setBack27("")
        setBack28("")
        setBack29("")
        setBack30("")
    }
    function setback24(){
        setBack1("")
        setBack2("")
        setBack3("")
        setBack4("")
        setBack5("")
        setBack6("")
        setBack7("")
        setBack8("")
        setBack9("")
        setBack10("")
        setBack11("")
        setBack12("")
        setBack13("")
        setBack14("")
        setBack15("")
        setBack16("")
        setBack17("")
        setBack18("")
        setBack19("")
        setBack20("")
        setBack21("")
        setBack22("")
        setBack23("")
        setBack24("orange")
        setBack25("")
        setBack26("")
        setBack27("")
        setBack28("")
        setBack29("")
        setBack30("")
    }
    function setback25(){
        setBack1("")
        setBack2("")
        setBack3("")
        setBack4("")
        setBack5("")
        setBack6("")
        setBack7("")
        setBack8("")
        setBack9("")
        setBack10("")
        setBack11("")
        setBack12("")
        setBack13("")
        setBack14("")
        setBack15("")
        setBack16("")
        setBack17("")
        setBack18("")
        setBack19("")
        setBack20("")
        setBack21("")
        setBack22("")
        setBack23("")
        setBack24("")
        setBack25("orange")
        setBack26("")
        setBack27("")
        setBack28("")
        setBack29("")
        setBack30("")
    }
    function setback26(){
        setBack1("")
        setBack2("")
        setBack3("")
        setBack4("")
        setBack5("")
        setBack6("")
        setBack7("")
        setBack8("")
        setBack9("")
        setBack10("")
        setBack11("")
        setBack12("")
        setBack13("")
        setBack14("")
        setBack15("")
        setBack16("")
        setBack17("")
        setBack18("")
        setBack19("")
        setBack20("")
        setBack21("")
        setBack22("")
        setBack23("")
        setBack24("")
        setBack25("")
        setBack26("orange")
        setBack27("")
        setBack28("")
        setBack29("")
        setBack30("")
    }
    function setback27(){
        setBack1("")
        setBack2("")
        setBack3("")
        setBack4("")
        setBack5("")
        setBack6("")
        setBack7("")
        setBack8("")
        setBack9("")
        setBack10("")
        setBack11("")
        setBack12("")
        setBack13("")
        setBack14("")
        setBack15("")
        setBack16("")
        setBack17("")
        setBack18("")
        setBack19("")
        setBack20("")
        setBack21("")
        setBack22("")
        setBack23("")
        setBack24("")
        setBack25("")
        setBack26("")
        setBack27("orange")
        setBack28("")
        setBack29("")
        setBack30("")
    }
    function setback28(){
        setBack1("")
        setBack2("")
        setBack3("")
        setBack4("")
        setBack5("")
        setBack6("")
        setBack7("")
        setBack8("")
        setBack9("")
        setBack10("")
        setBack11("")
        setBack12("")
        setBack13("")
        setBack14("")
        setBack15("")
        setBack16("")
        setBack17("")
        setBack18("")
        setBack19("")
        setBack20("")
        setBack21("")
        setBack22("")
        setBack23("")
        setBack24("")
        setBack25("")
        setBack26("")
        setBack27("")
        setBack28("orange")
        setBack29("")
        setBack30("")
    }
    function setback29(){
        setBack1("")
        setBack2("")
        setBack3("")
        setBack4("")
        setBack5("")
        setBack6("")
        setBack7("")
        setBack8("")
        setBack9("")
        setBack10("")
        setBack11("")
        setBack12("")
        setBack13("")
        setBack14("")
        setBack15("")
        setBack16("")
        setBack17("")
        setBack18("")
        setBack19("")
        setBack20("")
        setBack21("")
        setBack22("")
        setBack23("")
        setBack24("")
        setBack25("")
        setBack26("")
        setBack27("")
        setBack28("")
        setBack29("orange")
        setBack30("")
    }
    function setback30(){
        setBack1("")
        setBack2("")
        setBack3("")
        setBack4("")
        setBack5("")
        setBack6("")
        setBack7("")
        setBack8("")
        setBack9("")
        setBack10("")
        setBack11("")
        setBack12("")
        setBack13("")
        setBack14("")
        setBack15("")
        setBack16("")
        setBack17("")
        setBack18("")
        setBack19("")
        setBack20("")
        setBack21("")
        setBack22("")
        setBack23("")
        setBack24("")
        setBack25("")
        setBack26("")
        setBack27("")
        setBack28("")
        setBack29("")
        setBack30("orange")
    }

    async function Tisch11(){
            const Response = await fetch("/admin");
            const data = await Response.json();
            setEmail11(data)
            console.log(email11.fname)
    }
    async function Tisch12(){
        const Response2 = await fetch("/admin2");
        const data2 = await Response2.json();
        setEmail11(data2)
        console.log(email11.fname)
    }







    return(
        <>
            <Header/>
            <div className="kalender">
                <button onClick={setback1} className={back1}>01</button>
                <button onClick={setback2} className={back2}>02</button>
                <button onClick={setback3} className={back3}>03</button>
                <button onClick={setback4} className={back4}>04</button>
                <button onClick={setback5} className={back5}>05</button>
                <button onClick={setback6} className={back6}>06</button>
                <button onClick={setback7} className={back7}>07</button>
            </div>
            <div className="kalender">
                <button onClick={setback8} className={back8}>08</button>
                <button onClick={setback9} className={back9}>09</button>
                <button onClick={setback10} className={back10}>10</button>
                <button onClick={() => { setback11(); Tisch11(); }} className={back11}>11</button>
                <button onClick={() => { setback12(); Tisch12(); }} className={back12}>12</button>
                <button onClick={setback13} className={back13}>13</button>
                <button onClick={setback14} className={back14}>14</button>
            </div>
            <div className="kalender">
                <button onClick={setback15} className={back15}>15</button>
                <button onClick={setback16} className={back16}>16</button>
                <button onClick={setback17} className={back17}>17</button>
                <button onClick={setback18} className={back18}>18</button>
                <button onClick={setback19} className={back19}>19</button>
                <button onClick={setback20} className={back20}>20</button>
                <button onClick={setback21} className={back21}>21</button>
            </div>
            <div className="kalender">
                <button onClick={setback22} className={back22}>22</button>
                <button onClick={setback23} className={back23}>23</button>
                <button onClick={setback24} className={back24}>24</button>
                <button onClick={setback25} className={back25}>25</button>
                <button onClick={setback26} className={back26}>26</button>
                <button onClick={setback27} className={back27}>27</button>
                <button onClick={setback28} className={back28}onClick={setback28} className={back28}> 28</button>
            </div>
            <div className="kalender">
                <button onClick={setback29} className={back29}>29</button>
                <button onClick={setback30} className={back30}>30</button>

            </div>

            <h1>{email11.tischnummer}</h1>
        </>
    )

}

export default Admin;